import Head from "next/head";
import MovieList from "../components/MovieList";
import Parent from "../components/Parent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="content">
        <MovieList />
        <h1>This is Homepage</h1>

        <Parent />
      </div>
    </div>
  );
}
